base_url: "https://openrouter.ai/api/v1"
request_config:
    model: "deepseek/deepseek-r1"
    extra_body: 
        provider:
            order: 
                - DeepInfra
        allow_fallbacks: false
        include_reasoning: true