base_url: "https://openrouter.ai/api/v1"
prompt: "prompts/prompt_chat"
request_config:
    model: "deepseek/deepseek-r1"
    extra_body: 
        provider:
            order: 
                - Nebius
        allow_fallbacks: false
        include_reasoning: true